### ISSUE TITLE
Xpathresult is undefined in IE11

### ISSUE THREAD

**Issue by truonghoangnguyen** [futurepress/epub.js#212]
ie11 throw error:
```
'XPathResult' is undefined ReferenceError: 'XPathResult' is undefined
   at getTOC (http://localhost:8087/js/lib/epub_no_underscore.js:5610:4)
   at EPUBJS.Parser.prototype.toc (http://localhost:8087/js/lib/epub_no_underscore.js:5655:2)
   at Anonymous function (http://localhost:8087/js/lib/epub_no_underscore.js:2559:6)
   at invokeCallback (http://localhost:8087/js/lib/epub_no_underscore.js:1541:11)
   at publish (http://localhost:8087/js/lib/epub_no_underscore.js:1214:9)
   at publishFulfillment (http://localhost:8087/js/lib/epub_no_underscore.js:1631:7)
   at flush (http://localhost:8087/js/lib/epub_no_underscore.js:226:9)
```
workaround: 
 1. using XPath javascrip library http://code.google.com/p/wicked-good-xpath/
 2. call `wgxpath.install();` before open epub 

but still error on get TOC:

```
Object doesn't support property or method 'evaluate' TypeError: Object doesn't support property or method 'evaluate'
   at getTOC (http://localhost:8087/js/lib/epub_no_underscore.js:5631:4)
   at EPUBJS.Parser.prototype.toc (http://localhost:8087/js/lib/epub_no_underscore.js:5676:2)
   at Anonymous function (http://localhost:8087/js/lib/epub_no_underscore.js:2559:6)
   at invokeCallback (http://localhost:8087/js/lib/epub_no_underscore.js:1541:11)
   at publish (http://localhost:8087/js/lib/epub_no_underscore.js:1214:9)
   at publishFulfillment (http://localhost:8087/js/lib/epub_no_underscore.js:1631:7)
   at flush (http://localhost:8087/js/lib/epub_no_underscore.js:226:9)
```

**Comment by wangwy** [comment]
epub.js支持ie9吗？

**Comment by cattei** [comment]
不支持的，需要插件



cattei@outlook.com
 
From: wangwy
Date: 2015-04-22 10:50
To: futurepress/epub.js
Subject: Re: [epub.js] Xpathresult is undefined in IE11 (#212)
epub.js支持ie9吗？

**Comment by wangwy** [comment]
是因为ie9不支持column属性还是其他原因，如果需要插件的话是需要什么插件

**Comment by claytonk** [comment]
See https://github.com/futurepress/epub.js/issues/235#issuecomment-143008704 for changes need to get TOC working in IE

**Comment by fchasen** [comment]
Sorry the took so long to get fixed, but xpath in no longer used for TOC in the latest release here https://github.com/futurepress/epub.js/releases/tag/v0.2.11
