### ISSUE TITLE
Is it possible to open test.epub file directly to browser.

### ISSUE THREAD

**Issue by mbilwar** [futurepress/epub.js#221]
Hello,

i know it is silly question but i am facing difficulty to implement epub file directly open to browser without creating xhtml file and other required file. 

Current code is : 
<script>
        "use strict";

        document.onreadystatechange = function () {
           
            if (document.readyState == "complete") {
                EPUBJS.VERSION = "0.1.6";
           
                EPUBJS.filePath = "js/libs/";
                EPUBJS.cssPath = "../reader/css/";                           
                var reader = ePubReader("../reader/progit/"); // It's working but i have to maintain progit directory 
                //var reader = ePubReader("../reader/progit.epub"); //This code is commented. I am looking to open epub file direct
            }
        };

        </script>

Here, 
 var reader = ePubReader("../reader/progit/"); // It's working but i have to maintain progit directory 

I am looking to implement this without maintain progit directory directly open epub file like below i have written but its not woking in browser.
 
var reader = ePubReader("../reader/progit.epub"); 

It's giving me error in chrome :

Failed to load resource: the server responded with a status of 404 (Not Found)document.onreadystatechange @ search.html:22
epub.js:7553 _URL.createObjectURL is not a function TypeError: _URL.createObjectURL is not a function
    at EPUBJS.Unarchiver.getUrl (http://localhost:8080/reader/js/epub.min.js:7491:17)
    at EPUBJS.Chapter.url (http://localhost:8080/reader/js/epub.min.js:3586:10)
    at EPUBJS.Renderer.displayChapter (http://localhost:8080/reader/js/epub.min.js:6108:17)
    at EPUBJS.Book.displayChapter (http://localhost:8080/reader/js/epub.min.js:3027:25)
    at EPUBJS.Book.startDisplay (http://localhost:8080/reader/js/epub.min.js:2935:18)
    at http://localhost:8080/reader/js/epub.min.js:2919:18
    at invokeCallback (http://localhost:8080/reader/js/epub.min.js:1542:19)
    at publish (http://localhost:8080/reader/js/epub.min.js:1215:9)
    at publishFulfillment (http://localhost:8080/reader/js/epub.min.js:1632:7)
    at MutationObserver.flush (http://localhost:8080/reader/js/epub.min.js:227:9)(anonymous function) @ epub.js:7553
reader.min.map:1 GET http://localhost:8080/reader/js/reader.min.map 404 (Not Found)
hooks.min.map:1 GET http://localhost:8080/reader/js/hooks.min.map 404 (Not Found)
zip.min.map:1 GET http://localhost:8080/reader/js/libs/zip.min.map 404 (Not Found)

Thanks for help in advance :) :+1:

**Comment by fchasen** [comment]
Just to double check, have you included the zip library?
```<script src="/build/libs/zip.min.js"></script>```

**Comment by mbilwar** [comment]
I include this file but still not working. 

Here is my code:

<script src="../libs/jquery/jquery-2.1.0.js"></script>
   
   <script src="/build/libs/zip.min.js"></script>
    <script>
        "use strict";

        document.onreadystatechange = function () {
            debugger;
            if (document.readyState == "complete") {
                EPUBJS.VERSION = "0.1.6";
                debugger;
                EPUBJS.filePath = "js/libs/";
                EPUBJS.cssPath = "../reader/css/";
                // fileStorage.filePath = EPUBJS.filePath;
                debugger;
                //var reader = ePubReader("../reader/progit/");
                var reader = ePubReader("../reader/progit.epub");
                debugger;
            }
        };

        </script>
    
    <script src="/build/epub.min.js"></script>
    
    <script src="/build/hooks.min.js"></script>
    
    <script src="/build/reader.min.js"></script>
    
    <script src="../reader_src/plugins/search.js"></script>
    
    <script src="../reader/js/libs/screenfull.min.js"></script>
    
    <script src="../reader/js/libs/jquery.highlight.js"></script>
    <script src="../hooks/extensions/highlight.js"></script>

I want to read this file var reader = ePubReader("../reader/progit.epub");  progit.epub file but its not opening. 

It giving error like this:  ONLY (1 ERROR NOW) :)

h.createObjectURL is not a function TypeError: h.createObjectURL is not a function
    at EPUBJS.Unarchiver.getUrl (http://localhost:8080/build/epub.min.js:3:29473)
    at EPUBJS.Chapter.url (http://localhost:8080/build/epub.min.js:2:12589)
    at EPUBJS.Renderer.displayChapter (http://localhost:8080/build/epub.min.js:3:12710)
    at EPUBJS.Book.displayChapter (http://localhost:8080/build/epub.min.js:2:4217)
    at EPUBJS.Book.startDisplay (http://localhost:8080/build/epub.min.js:2:3098)
    at http://localhost:8080/build/epub.min.js:2:2864
    at p (http://localhost:8080/build/epub.min.js:1:19428)
    at o (http://localhost:8080/build/epub.min.js:1:19347)
    at u (http://localhost:8080/build/epub.min.js:1:20077)
    at MutationObserver.e (http://localhost:8080/build/epub.min.js:1:15100)

If i used var reader = ePubReader("../reader/progit/");  then it will work find but it take all xhtml file from folder called /progit/ . 

Thank for help @fchasen Appreciated :)

**Comment by mbilwar** [comment]
Thank you so much for all help. 

It's Work :) :+1:

**Comment by casic** [comment]
Where is now  build  folder ????
