### ISSUE TITLE
No RootFile Found // basePath is undefined

### ISSUE THREAD

**Issue by Neamar** [futurepress/epub.js#228]
Hi,

Using the latest (0.2.5) `epub.min.js` with `zip.min.js`, i get the following error when loading an epub (not all epubs):

```
No RootFile Found
VM46129:2 Cannot read property 'basePath' of undefined TypeError: Cannot read property 'basePath' of undefined
    at eval (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:27800)
    at p (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:19428)
    at o (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:19347)
    at u (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:20077)
    at MutationObserver.e (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:15100)
VM46129:1 Could not load book at: META-INF/container.xml
2VM46129:2 Cannot read property 'basePath' of undefined TypeError: Cannot read property 'basePath' of undefined
    at eval (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:27800)
    at p (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:19428)
    at o (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:19347)
    at u (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:20077)
    at MutationObserver.e (eval at <anonymous> (http://localhost:3000/javascripts/vendor/jquery.js:612:22), <anonymous>:1:15100)
```

![no-root-file](https://cloud.githubusercontent.com/assets/536844/8285229/4cb48c48-1902-11e5-90ef-0c9ca381c303.png)

The epub is not free, so i can't post it here, however if someone ask i can send it by email for debugging purposes. Unless of course i'm doing something wrong ;)

**Comment by bdhawks** [comment]
Hi, I am having the same exact error with a few ePub files. Were you able to resolve this issue yet on your own?

**Comment by fchasen** [comment]
Could you unzip the epub and inspect the `META-INF/container.xml` file.
Is there a node in there called `rootfile`?

**Comment by JakeHartnell** [comment]
No follow up in over 2 years... closing for now.
