### ISSUE TITLE
TypeError: EPUBJS.core.getMimeType is not a function

### ISSUE THREAD

**Issue by squ1b3r** [futurepress/epub.js#233]
Using the code from master branch and the exact setup from https://github.com/futurepress/epub.js/blob/master/reader/dev.html doesn't seem to be working. It shows a title of the book and the TOC is also available but the book itself won't render. In chrome console there is an error which pops up upon page load:
```
book.js:1286 EPUBJS.core.getMimeType is not a function TypeError: EPUBJS.core.getMimeType is not a function
    at EPUBJS.Unarchiver.getUrl (http://localhost:8000/static/javascripts/lib/epubjs/src/unarchiver.js:53:62)
    at EPUBJS.Chapter.url (http://localhost:8000/static/javascripts/lib/epubjs/src/chapter.js:63:10)
    at EPUBJS.Renderer.displayChapter (http://localhost:8000/static/javascripts/lib/epubjs/src/renderer.js:107:17)
    at null.<anonymous> (http://localhost:8000/static/javascripts/lib/epubjs/src/book.js:376:10)
    at EPUBJS.Book.generatePageList (http://localhost:8000/static/javascripts/lib/epubjs/src/book.js:404:17)
    at http://localhost:8000/static/javascripts/lib/epubjs/src/book.js:420:8
    at invokeCallback (http://localhost:8000/static/javascripts/lib/epubjs/libs/rsvp/rsvp.js:1541:19)
    at publish (http://localhost:8000/static/javascripts/lib/epubjs/libs/rsvp/rsvp.js:1214:9)
    at publishFulfillment (http://localhost:8000/static/javascripts/lib/epubjs/libs/rsvp/rsvp.js:1631:7)
    at MutationObserver.flush (http://localhost:8000/static/javascripts/lib/epubjs/libs/rsvp/rsvp.js:226:9)
```
Am I missing something here?

Also, it's really confusing that in all example there are `ePub` and 'ePubReader' being used on different pages but the documentation gives information only for `ePub`. What is the difference? From what I can see `ePub` is a really simple viewer and 'ePubReader' supports a bunch of plugins.

**Comment by squ1b3r** [comment]
Turned out that the `mime-types.js` which is in the `/libs/jszip/` forlder is somehow broken. The one in /libs/mime-types/' works fine.
