### ISSUE TITLE
What about incorrect epub files?

### ISSUE THREAD

**Issue by paulocheque** [futurepress/epub.js#465]
I am having issues when an image is missing inside the epub file. It appears all stop working. Any ideas? Sometimes I am getting 100% of the CPU too.

`File not found in the epub`

```
Error
    at u.Unarchiver.getUrl (/static/js/vendor.b3b2a9d2696adbaf5376.js:55:28137)
    at u.replace.srcs (/static/js/vendor.b3b2a9d2696adbaf5376.js:55:22290)
    at /static/js/vendor.b3b2a9d2696adbaf5376.js:54:5459
    at .<anonymous> (/static/js/vendor.b3b2a9d2696adbaf5376.js:54:4727)
    at Array.forEach (native)
    at u.Chapter.replace (/static/js/vendor.b3b2a9d2696adbaf5376.js:54:4635)
    at u.Chapter.replaceWithStored (/static/js/vendor.b3b2a9d2696adbaf5376.js:54:5033)
    at u.replace.resources (/static/js/vendor.b3b2a9d2696adbaf5376.js:55:22092)
    at /static/js/vendor.b3b2a9d2696adbaf5376.js:54:21087
    at Array.forEach (native)"
```

**Comment by fchasen** [comment]
Ah I suppose we should throw an error if an asset is missing, and add an option to ignore that error in the settings.

Do you have a epub to test with? Otherwise I can make on and attach it to this issue.

**Comment by paulocheque** [comment]
Unfortunately I am using a book without a free license, so I can not share it.

I guess the settings is not necessary. We could always display an error in the console like "file X is missing in the epub file", and the reader can ignore completely this error, so everything else will continue to work as normal. Just a 

Something like:

```
try {
    loadAsset(url)
} catch(e) {
    console.error('asset $URL not found (404)')
}
```

**Comment by paulocheque** [comment]
I found a free book that has this kind of issue.

You can use this url to download it: https://dl.dropboxusercontent.com/u/2694558/unix-guide-powershell.epub

**Comment by paulocheque** [comment]
Do you know if this issues has been fixed in the 0.3 branch? 

Thanks in advance

**Comment by gimox** [comment]
if you need to render epub without stop it in a dirty way: 

replace Unarchivier.getUrl  with this (you need to patch storage if needed):

```js
EPUBJS.Unarchiver.prototype.getUrl = function(url, mime) {
    var unarchiver = this;
    var deferred = new RSVP.defer();
    var decodededUrl = window.decodeURIComponent(url);
    var entry = this.zip.file(decodededUrl);
    var _URL = window.URL || window.webkitURL || window.mozURL;
    var tempUrl;
    var blob;

    if (!entry) {
        /*
        deferred.reject({
        	message : "File not found in the epub: " + url,
        	stack : new Error().stack
        });
        return deferred.promise;
        */
				console.log("File not found in the epub:" + url);
        deferred.resolve("");
        return deferred.promise;
    }
```

**Comment by paulocheque** [comment]
I end up with the same solution: `deferred.resolve(null);`. No pretty though, hacking the library.

I believe this is the most critical issue right now, because it prevent the reader to read epub files and the CPU go crazy on 100%.
