### ISSUE TITLE
RSVP is not defined error

### ISSUE THREAD

**Issue by owen26** [futurepress/epub.js#622]
I'm using Ionic 3 framework for a project and I want to import epub.js library from npm.

The problem is it always shows "RSVP is not defined error" and I have no idea what to do.

Ionic 3 powered by angular-cli, hence WEBPACK.

```
ReferenceError: RSVP is not defined
    at Object.<anonymous> (http://localhost:8100/build/main.js:120462:1)
    at Object.exports.read.eLen (http://localhost:8100/build/main.js:125616:30)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.webpackEmptyContext.keys (http://localhost:8100/build/main.js:61405:80)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:36508:69)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:89053:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:88692:73)
```

Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 6.9.5
OS Platform: macOS Sierra
Navigator Platform: MacIntel

**Comment by aokhotnikov** [comment]
I have the same problem

**Comment by xiaozhaoqi** [comment]
I have the same problem,too.  There is no solution on internet.
But, if i use a single HTML page with epub.js, it works;
if i use React(render the epub in JSX ) with epub.js, it will report "ReferenceError: RSVP is not defined".
so, i have to use a HTML page with epub.js  at present.

**Comment by manjudr** [comment]
<img width="717" alt="screen shot 2018-09-19 at 12 44 55 pm" src="https://user-images.githubusercontent.com/16288575/45736873-e22b0d80-bc09-11e8-9143-9304a89296a1.png">
Even me too facing the same issue with the webpack

@owen26 Any update on this issue? Still are you facing this problem?

**Comment by fchasen** [comment]
I think you must be using an older version, can you try the latest release on NPM or github?

**Comment by manjudr** [comment]
@fchasen  Thanks for the response.

After defining like this in my webpack then it's started working.

```
new webpack.ProvidePlugin({
            RSVP: 'rsvp',
})
```

added `rsvp(4.8.4)` as dependency in my package.json

**Comment by ksrb** [comment]
For those tumbleweed running into this issue this project has a older version published in npm with the name `epub.js` that is 2 years old. If you install that one and try to import it it won't work

So make sure in your `package.json` you have:
```
    "epubjs": "xxx",
```
And not
```
    "epub.js": "xxx",
```
# References
https://www.npmjs.com/package/epubjs - LATEST
https://www.npmjs.com/package/epub.js - OLDER VERSION

# Additional Details
I was using this older version thinking it was the latest and trying to import the library via:
```tsx
import epub from "epub.js/build/epub";
```
Which you shown the RSVP not defined error.
